[package]
name = "gsi-csgo"
version = "0.1.0"
edition = "2021"
authors = ["Sam Miller"]
readme = "README.md"
license-file = "LICENSE"

[dependencies]
poem = "1.3.48"
tokio = {version = "1.21.2", features = ["rt-multi-thread", "macros"]}
tracing-subscriber = "0.3.16"